version: '2'

#NETWORKING#################################################################
# By default Compose will set up a private network for the cluster #########
# Each container will join the network and can be reached by other #########
# containers at a host-name identical to the containres name       #########
# It's necessary to keep the master container_name as 'master'     #########
############################################################################
 
services:
  master:
    build: .
    networks:
      - default
    image: mengwangk/myinvestor-spark
    container_name: myinvestor-engine
    ports:
      - "8080:8080"
      - "7077:7077"
      - "8081:8081"
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/master.conf"]
#---------------------------------------
  slave:
    image: mengwangk/myinvestor-spark
    depends_on:
      - master
    command: ["/usr/bin/supervisord", "--configuration=/opt/conf/slave.conf"]

networks:
  default:
    external:
      name: spark-network