/**
 * Get stock information
 * 
 * Pass in the name of the stock
 * 
 * The output file is "stock_symbol".json.
 * 
 */

"use strict";

String.prototype.format = String.prototype.f = function () {
    var s = this,
        i = arguments.length;

    while (i--) {
        s = s.replace(new RegExp('\\{' + i + '\\}', 'gm'), arguments[i]);
    }
    return s;
};

var GOOGLE_FINANCE_URL_GET_STOCK_INFO = 'https://www.google.com/finance?q={0}:{1}&sq=%5B(exchange+%3D%3D+%22{2}%22)%5D&sp=1&ei=YAr5V6qTEYPTuATt-ZfYAw';

var system = require('system'),
    webPage = require('webpage'),
    timestamp;

var fs = require('fs');


var stockSymbolFileName = '';
if (system.args.length === 1) {
    console.log('Pass in the name of the stock symbol file generated by getStockSymbols.js');
    phantom.exit(1);
} else {
    timestamp = Date.now();
    stockSymbolFileName = system.args[1];
    var exchangeName = stockSymbolFileName.split('.')[0];
    console.log('Getting stock symbols for [' + exchangeName + ']');

    // Read the file
    try {
        var content = fs.read(stockSymbolFileName);
        var stocks = JSON.parse(content);

        // Create a folder named after the exchange name
        if (!fs.exists(exchangeName) || (fs.exists(exchangeName) && !fs.isDirectory(exchangeName))) {
            if (fs.makeDirectory(exchangeName)) {
                console.log('Created the folder [' + exchangeName + ']');
            } else {
                console.log('Unable to create folder [' + exchangeName + ']');
            }
        } else {
            console.log('Folder [' + exchangeName + '] already exists');
        }

        if (Array.isArray(stocks)) {
            var counter = 0;
            //for (var counter = 0; counter < 3; counter++) {
            //var counter = 3;
            //    var stock = stocks[counter];
            getStockInfo(stocks, counter);

            // }
        } else {
            phantom.exit(1);
        }
    } catch (e) {
        console.log('Unable to get stock history.');
        console.log(e.message);
        phantom.exit(1);
    }
    //
}

function getStockInfo(stocks, counter) {
    var stock = stocks[counter];
    console.log('Retrieving stock info for [' + stock.company + ']');
    var stockInfoUrl = GOOGLE_FINANCE_URL_GET_STOCK_INFO.format(exchangeName, encodeURIComponent(stock.symbol), exchangeName);
    console.log(stockInfoUrl);
    var page = webPage.create();
    page.open(stockInfoUrl, function (status) {
        if (status !== 'success') {
            console.log('Unable to access network');
        } else {
            console.log("okay");
            var title = page.evaluate(function () {
                return document.title;
            });
            console.log(title);
        }
        page.close();
        //if (counter === (stocks.length - 1)) {
        if (counter == 2) {
            timestamp = Date.now() - timestamp;
            console.log('Total time: ' + (timestamp / 1000) + ' seconds');
            phantom.exit();
        } else {
            getStockInfo(stocks, ++counter);
        }
    });
}



