/**
 * Read a "exchange.json" file and output the stock history for each
 * stock into a "stock_symbol".json file.
 * 
 * The stock symbols file.
 * 
 */
"use strict";

String.prototype.format = String.prototype.f = function () {
    var s = this,
        i = arguments.length;

    while (i--) {
        s = s.replace(new RegExp('\\{' + i + '\\}', 'gm'), arguments[i]);
    }
    return s;
};

var GOOGLE_FINANCE_URL_GET_STOCK_HISTORY = 'http://www.google.com/finance/historical?q={0}%3A{1}&ei=zsb0V4H5K5LQuATWx7_oDQ&output=csv';

var system = require('system'),
    page = require('webpage').create(),
    timestamp,
    historicalDataUrl;

var fs = require('fs');

// Log to console in PhantomJS sandbox
page.onConsoleMessage = function (msg) {
    system.stderr.writeLine('console: ' + msg);
};
var stockSymbolFileName = '';
if (system.args.length === 1) {
    console.log('Pass in the name of the stock symbol file generated by getStockSymbols.js');
    phantom.exit(1);
} else {
    timestamp = Date.now();
    stockSymbolFileName = system.args[1];
    var exchangeName = stockSymbolFileName.split('.')[0];
    console.log('Getting stock symbols for [' + exchangeName + ']');

    // Read the file
    try {
        var content = fs.read(stockSymbolFileName);
        var stocks = JSON.parse(content);

        // Create a folder named after the exchange name
        if (!fs.exists(exchangeName) || (fs.exists(exchangeName) && !fs.isDirectory(exchangeName))) {
            if (fs.makeDirectory(exchangeName)) {
                console.log('Created the folder [' + exchangeName + ']');
            } else {
                console.log('Unable to create folder [' + exchangeName + ']');
            }
        } else {
            console.log('Folder [' + exchangeName + '] already exists');
        }

        if (Array.isArray(stocks)) {
            //for (var counter = 0; counter < stocks.length; counter++) {
                var counter = 0;
                var stock = stocks[counter];
                // Get historical price for each stock
                historicalDataUrl = GOOGLE_FINANCE_URL_GET_STOCK_HISTORY;
                historicalDataUrl = historicalDataUrl.format(exchangeName, stock.symbol);
                console.log('Retrieving historical data for [' + stock.company + ']');
                console.log(historicalDataUrl);
                page.open(historicalDataUrl, function (status) {
                   // if (status !== 'success') {
                   //     console.log('Failed to load the address');
                   // } else {
                        // Actual extraction logic here                 
                        console.log(page.plainText);
                    //}

                    timestamp = Date.now() - timestamp;
                    console.log('Total time: ' + (timestamp / 1000) + ' seconds');
                    phantom.exit();
                });
            //}
        } else {
            phantom.exit(1);
        }

    } catch (e) {
        console.log('Unable to get stock history.');
        console.log(e.message);
        phantom.exit(1);
    }






}


